title: Exploring Ruby on Rails
description: Personal blog

url: https://gryffindor.in
baseurl: ""
paginate_path: "blog/page:num/"
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
    
social:
  github: SGourshete
  twitter: gourshete
  facebook: swapnil.gourshete.5
  email: learning.swapnil@gmail.com

google_analytics: "UA-141780310-1"